name: Build and Push App

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'app/**'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t cafecrunch/3c3b75e49fd9:latest .

    - name: Push to Docker Hub
      run: docker push cafecrunch/3c3b75e49fd9:latest
